
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package de.bitapp.paper.page;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-05-25T12:40:52.957+09:00
 * Generated source version: 3.0.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "pageService",
                      portName = "pageServicePort",
                      targetNamespace = "http://paper.bitapp.de/page",
                      wsdlLocation = "file:/C:/Users/bond/workspace/PaperTest1/paper.wsdl",
                      endpointInterface = "de.bitapp.paper.page.PageServicePortType")
                      
public class PageServicePortTypeImpl implements PageServicePortType {

    private static final Logger LOG = Logger.getLogger(PageServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see de.bitapp.paper.page.PageServicePortType#ping(de.bitapp.paper.page.StatusCodeTyp  status )*
     */
    public void ping(javax.xml.ws.Holder<StatusCodeTyp> status) { 
        LOG.info("Executing operation ping");
        System.out.println(status.value);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
