package de.bitapp.paper.page;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-05-25T12:40:53+09:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://paper.bitapp.de/page", name = "pageServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PageServicePortType {

    @WebMethod(operationName = "Ping", action = "Ping")
    public void ping(
        @WebParam(partName = "Status", mode = WebParam.Mode.INOUT, name = "Status")
        javax.xml.ws.Holder<StatusCodeTyp> status
    );
}
